### ISSUE TITLE
Arrow keys on contentEditable

### ISSUE THREAD

**Issue by JohnMcLear** [dwachss/bililiteRange#5] opened 2015-01-14 20:18 UTC
Should arrow keys work with sendkeys?  I don't see them working :(

**Comment by dwachss** [comment] 2015-01-14 20:27
{leftarrow} and {rightarrow} work (though I'm in the process of renaming them to the proposed DOM3 standard, {ArrowLeft} and {ArrowRight}. Up and down arrows do not; I'm not sure how to implement that. How do I tell  what character is right above the insertion point?

**Comment by JohnMcLear** [comment] 2015-01-14 20:34
Should leftarrow and rightarrow be able to go from line 1 to line 2?

**Comment by dwachss** [comment] 2015-01-14 20:39
I'm having no problems with it on http://bililite.com/blog/2011/01/23/improved-sendkeys/ or the kavanot.me editor. Is it a new problem?

**Comment by JohnMcLear** [comment] 2015-01-15 23:18
I get a problem with the following test:

```
describe("As the caret is moved is the UI properly updated?", function(){
  var padName;
  var numberOfRows = 50;

  //create a new pad before each test run
  beforeEach(function(cb){
    helper.newPad(cb);
    this.timeout(60000);
  });

  it("creates a pad", function(done) {
    padName = helper.newPad(done);
    this.timeout(60000);
  });

  /*
  it("right arrow", function(done){
    var inner$ = helper.padInner$;
    var chrome$ = helper.padChrome$;

    var $newFirstTextElement = inner$("div").first();
    $newFirstTextElement.text("foo");
    $newFirstTextElement.focus();
    $newFirstTextElement.sendkeys('{rightarrow}');

    helper.waitFor(function(){ // Wait for the DOM to register the new items
      var pos = caretPosition(inner$);
      return pos.anchorOffset == 1;
    }).done(function(){ // Once the DOM has registered the items
      done();
    });
  });
  */

  it("Next line on right arrow", function(done){
    var inner$ = helper.padInner$;
    var chrome$ = helper.padChrome$;

    var $newFirstTextElement = inner$("div").first();
    $newFirstTextElement.text("foo");
    var $editor = inner$("body");
//    console.log($editor);
    $newFirstTextElement.focus();
    $editor.parent().sendkeys('{rightarrow}');
    $editor.parent().sendkeys('{rightarrow}');
    $editor.parent().sendkeys('{rightarrow}');
  //  $editor.parent().sendkeys('{rightarrow}');
  // If I pass this forth sendkeys event the caret jumps 3 caret positions to the right!

    helper.waitFor(function(){ // Wait for the DOM to register the new items
      var pos = caretPosition(inner$);
      return pos.anchorOffset == 1;
    }).done(function(){ // Once the DOM has registered the items
      done();
    });

  });
});
```

See this comment..
``  // If I pass this forth sendkeys event the caret jumps 3 caret positions to the right!``

The first 3 events are handled properly ;\

It's as if EP is treating new lines/ line breaks as not existing when trying to use sendkeys...  Any ideas?

To replicate install etherpad, put the contents of the above into ``caret.js`` in your ``/tests/frontend/specs`` folder and visit ``http://127.0.0.1:9001/tests/frontend/?grep=caret.js``

**Comment by dwachss** [comment] 2015-01-16 02:39
I'm not going to have time to look through all of etherpad, but I looked at the public site (beta.etherpad.org) and I think I know what the problem is. 
`bililiteRange` deals with text, not elements. The `span`s and `div`s of a `contenteditable` element are problems to get around, and do not mark separate paragraphs; there is no linebreak character there.
Etherpad creates a new `DIV` with each enter key; it does not insert a `'\n'`. This is not a problem for Etherpad but you have to take it into account if you are using `bililiteRange` for testing.

In my editor (see, e.g. http://kavanot.me/Lorem+Ipsum/edit ) I use a `PRE` element with `white-space: pre-wrap`, and catch keydown and paste events to insert newlines rather than creating new elements. See `bililiteRange.fancyText.js`.

If you think that this is what is going on, I will close this as "working as intended". Thanks for looking at the code so closely!

**Comment by JohnMcLear** [comment] 2015-01-16 02:53
Yeah that's what's going on .  Looks like I won't be able to use sendkeys for my tests then.  We should add this caveat to a wiki or so :)
----- Reply message -----

**Comment by dwachss** [comment] 2015-01-16 03:42
OK. You may still be able to use sendkeys for testing since you know what the result is "supposed" to be, but that's up to you.
The trick with catching `keydown` and inserting newlines is what Lea Verou uses in [Dabblet](http://dabblet.com); I don't know if it's worth using with Etherpad.

**Comment by dwachss** [comment] 2015-01-16 03:42
Closed; working as intended

**Closed by dwachss** 2015-01-16 03:42 UTC
